import {roundaboutChoices} from './dist/roundabouts.js';
import {createFreeDrive} from './dist/free-drive.js';
import {createMusic} from './dist/music.js';
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import * as T from './dist/vendor/three.js';
const data=JSON.parse(fs.readFileSync('dist/map.json','utf8'));const elements=new Map();const tools=new Map(),listeners=new Map();let raf=[],now=0;
const context=new Proxy({},{get:(o,p)=>p==='measureText'?()=>({width:20}):()=>{}});
function element(id){if(!elements.has(id))elements.set(id,{id,hidden:false,textContent:'',style:{},classList:{add(){},remove(){},toggle(){}},dataset:{},children:[],events:new Map(),append(...v){this.children.push(...v)},replaceChildren(){this.children=[]},setAttribute(){},getContext(){return context},addEventListener(type,fn){this.events.set(type,fn);},showModal(){this.open=true},close(){this.open=false;this.events.get('close')?.();},width:700,height:520});return elements.get(id);}
const document={getElementById:element,createElement:t=>({ ...element('new'+Math.random()),tagName:t}),body:element('body'),addEventListener(){},modelContext:{registerTool:t=>tools.set(t.name,t)}};
const terrain=data.terrain;function height(x,z){let a=Math.max(0,Math.min(terrain.nx-1.001,(x-terrain.x0)/40)),b=Math.max(0,Math.min(terrain.nz-1.001,(z-terrain.z0)/40)),i=Math.floor(a),j=Math.floor(b),u=a-i,v=b-j,h=terrain.heights;return(h[j*terrain.nx+i]*(1-u)+h[j*terrain.nx+i+1]*u)*(1-v)+(h[(j+1)*terrain.nx+i]*(1-u)+h[(j+1)*terrain.nx+i+1]*u)*v;}
const env={document,window:{addEventListener:(name,fn)=>listeners.set(name,fn)},location:{reload(){}},console,T,roundaboutChoices,createFreeDrive,createMusic,createWorld:()=>({height,resetCamera(){},setTurnArrow(){},update(){}}),fetch:async()=>({ok:true,json:async()=>data}),setTimeout:()=>0,clearTimeout(){},requestAnimationFrame:cb=>raf.push(cb),performance:{now:()=>now},Promise,Math,Map,Set,Number,Infinity,Error};
const ctx=vm.createContext(env);const source=fs.readFileSync('dist/game.js','utf8').replace(/^import .*?;\n/gm,'');const init=vm.runInContext(`(async()=>{${source}})()`,ctx);for(let i=0;i<12;i++){await Promise.resolve();const q=raf.splice(0);q.forEach(cb=>cb(now));}await init;assert.equal(element('start').disabled,false);const read=()=>tools.get('read_drive_state').execute();const act=(name,input)=>tools.get(name).execute(input);
assert.equal(read().state,'intro');act('start_drive');assert.equal(read().state,'decision');const before=read();assert.throws(()=>act('choose_road',{edgeId:-1}));assert.equal(read().currentNode,before.currentNode);console.log('Start + invalid choice: OK');
function step(){now+=45;const q=raf.splice(0);q.forEach(cb=>cb(now));}
let choices=0,peak=0;while(read().state!=='finished'&&choices<180){let s=read();if(s.state==='decision'){const e=s.choices.find(c=>c.recommended);assert.ok(e,'Every junction has route home');act('choose_road',{edgeId:e.id});choices++;if(choices===2){element('pause').onclick();const old=read().travelledMetres;for(let i=0;i<20;i++)step();assert.equal(read().travelledMetres,old);element('pause').onclick();console.log('Pause freezes motion: OK');}}
 for(let i=0;i<600&&read().state==='driving';i++){step();peak=Math.max(peak,read().speedKmh);assert.ok(read().speedKmh<=200);}}
assert.equal(read().state,'finished');assert.ok(read().travelledMetres>2900&&read().travelledMetres<3400);assert.equal(element('finish').hidden,false);console.log('Full route arrival: OK',read(),{choices});
assert.ok(peak>=195,'Automatic acceleration must approach 200 without touching any speed selector');
// The first arrival unlocks the colour picker: the button leads to the start screen, where it is shown.
assert.equal(element('unlock').hidden,false);assert.match(element('again').textContent,/farge/);
element('again').onclick();assert.equal(read().state,'intro');assert.equal(element('welcome').hidden,false);assert.equal(element('rewards').hidden,false);
act('start_drive');assert.equal(read().state,'decision');assert.equal(read().travelledMetres,0);console.log('Replay via the start screen after the first reward: OK');
let off=false;for(let k=0;k<8&&!off;k++){const s=read();const other=s.choices.find(c=>!c.recommended);if(other){act('choose_road',{edgeId:other.id});off=true;}else act('choose_road',{edgeId:s.choices[0].id});for(let j=0;j<5000&&read().state==='driving';j++)step();}assert.ok(off);assert.ok(read().choices.some(c=>c.recommended));console.log('Detour retains route guidance: OK');
element('driveMode').onchange({target:{value:'free'}});assert.equal(read().state,'free');assert.equal(element('worldArrows').hidden,true);assert.equal(element('freeControls').hidden,false);for(let i=0;i<25;i++)step();
const key=(type,code)=>listeners.get(type)({code,key:code==='Space'?' ':code,preventDefault(){},repeat:false});key('keydown','Space');key('keydown','ArrowRight');for(let i=0;i<8;i++)step();assert.equal(read().paused,false);assert.equal(read().drifting,true);key('keyup','Space');key('keyup','ArrowRight');step();assert.equal(read().drifting,false);
const pointer=(id,type,n)=>element(id).events.get(type)({pointerId:n,preventDefault(){}});pointer('freeLeft','pointerdown',1);pointer('freeDrift','pointerdown',2);step();assert.equal(read().drifting,true);pointer('freeDrift','pointercancel',2);pointer('freeLeft','pointerup',1);step();assert.equal(read().drifting,false);pointer('freeBrake','pointerdown',3);const beforeBrake=read().speedKmh;for(let i=0;i<10;i++)step();assert.ok(read().speedKmh<beforeBrake);pointer('freeBrake','pointerup',3);
element('pause').onclick();const frozen=read().position;for(let i=0;i<20;i++)step();assert.deepEqual(read().position,frozen);element('pause').onclick();key('keydown','ArrowLeft');listeners.get('blur')();assert.equal(read().paused,true);element('pause').onclick();key('keydown','KeyQ');assert.equal(read().speedKmh,0);
const [qx,qz]=read().position;let roadDistance=Infinity;for(const r of data.roads)for(let i=1;i<r.p.length;i++){const [ax,az]=r.p[i-1],[bx,bz]=r.p[i],dx=bx-ax,dz=bz-az,t=Math.max(0,Math.min(1,((qx-ax)*dx+(qz-az)*dz)/(dx*dx+dz*dz||1)));roadDistance=Math.min(roadDistance,Math.hypot(qx-ax-t*dx,qz-az-t*dz));}assert.ok(roadDistance<.001,'Q snaps the car to a road');
element('driveMode').onchange({target:{value:'route'}});assert.equal(read().state,'decision');assert.equal(element('freeControls').hidden,true);assert.equal(read().currentNode,data.start);console.log('Mode switch, Space drift without pause, key release, blur pause, recovery and return to route: OK');
